# -*- coding: utf-8 -*-
"""swot kovrizhnykh.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DSI0X1zABI-ji_aTS1ymv6li8IRtQX1F
"""

print('Группа: 20БИ2; ФИО: Коврижных Николай Андреевич')
!ln -fs /usr/share/zoneinfo/Europe/Moscow/etc/localtime
print("Дата выполнения задания:")
!date

from google.colab import drive
drive.mount('/content/drive')
import os
print(os.getcwd())
print(os.listdir('./'))
print(os.listdir('/content/drive'))
print(os.listdir('/content/drive/MyDrive/Colab Notebooks'))
print ("Бизнес-идея: Открытие частной стоматологии")

from google.colab import auth
auth.authenticate_user()
import gspread
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())
table = gc.open_by_key('1CO5Nf6SOO5L3sBK7EGbt4T3PaCjl_xmhY_Z9PLVZ2zw')
worksheet = table.worksheet("Лист1")

rows = worksheet.get_all_values()
strenghts = list()
actions = list()
importance = list()
probability = list()
power = list()

i=0
for row in rows:
  if(i>0):
    print (i, row)
    strenghts.append(row[1])
    actions.append(row[2])
    importance.append(int(row[3]))
    probability.append(float(row[4]))
  
  i+=1
print('\n',strenghts, actions, importance, probability, sep='\n', end='\n\n')

import matplotlib.pyplot as plt
fig=plt.figure(figsize=(16,12), dpi=75)
plt.title('Сильные стороны',fontsize=40)
plt.xlabel('Свойства',fontsize=25)
plt.ylabel('Важность',fontsize=25)
plt.bar (strenghts, probability, width=0.6)
plt.xticks(strenghts, fontsize=14)

plt.grid(True, color='r', linestyle='-', linewidth=0.6)
plt.show

rows = worksheet.get_all_values()
weaknesses = list()
actions = list()
importance = list()
probability = list()
power = list()

i=0
for row in rows:
  if(i>0):
    print (i, row)
    weaknesses.append(row[6])
    actions.append(row[7])
    importance.append(int(row[8]))
    probability.append(float(row[9]))
  
  i+=1
print('\n',weaknesses, actions, importance, probability, sep='\n', end='\n\n')

import matplotlib.pyplot as plt
fig=plt.figure(figsize=(15,13), dpi=70)
plt.title('Слабые стороны',fontsize=30)
plt.xlabel('Свойства',fontsize=20)
plt.ylabel('Важность',fontsize=20)
plt.bar (weaknesses, probability, width=0.5)
plt.xticks(weaknesses, fontsize=15)

plt.grid(True, color='r', linestyle='-', linewidth=0.8)
plt.show

rows = worksheet.get_all_values()
opportunities = list()
actions = list()
importance = list()
probability = list()
power = list()

i=0
for row in rows:
  if(i>0):
    print (i, row)
    opportunities.append(row[11])
    actions.append(row[12])
    importance.append(int(row[13]))
    probability.append(float(row[14]))
  
  i+=1
print('\n',opportunities, actions, importance, probability, sep='\n', end='\n\n')


import matplotlib.pyplot as plt
fig=plt.figure(figsize=(15,13), dpi=70)
plt.title('Возможности',fontsize=35)
plt.xlabel('Свойства',fontsize=20)
plt.ylabel('Важность',fontsize=20)
plt.bar (opportunities, probability, width=0.7)
plt.xticks(opportunities, fontsize=10)

plt.grid(True, color='r', linestyle='-', linewidth=0.8)
plt.show

rows = worksheet.get_all_values()
threats = list()
actions = list()
importance = list()
probability = list()
power = list()

i=0
for row in rows:
  if(i>0):
    print (i, row)
    threats.append(row[16])
    actions.append(row[17])
    importance.append(int(row[18]))
    probability.append(float(row[19]))
  
  i+=1
print('\n',threats, actions, importance, probability, sep='\n', end='\n\n')

import matplotlib.pyplot as plt
fig=plt.figure(figsize=(15,13), dpi=70)
plt.title('Угрозы',fontsize=35)
plt.xlabel('Свойства',fontsize=20)
plt.ylabel('Важность',fontsize=20)
plt.bar (threats, probability, width=0.6)
plt.xticks(threats, fontsize=10)

plt.grid(True, color='r', linestyle='-', linewidth=0.8)
plt.show

rows = worksheet.get_all_values()
Power_strenghts = list()
Power_weak = list()
Power_opport = list()
Power_threats = list()

i=0
for row in rows:
  if(i>0):
    print (i, row)
    Power_strenghts.append(float(row[5]))
    Power_weak.append(float(row[10]))
    Power_opport.append(float(row[15]))
    Power_threats.append(float(row[20]))
  
  i+=1

print('\n',Power_strenghts, Power_weak, Power_opport, Power_threats, sep='\n', end='\n\n')
sum_strenghts = sum(Power_strenghts)
sum_weak = -sum(Power_weak)
sum_opport = sum(Power_opport)
sum_threats = -sum(Power_threats)

print(sum_strenghts,sum_weak,sum_opport,sum_threats)
sum_power=(sum_strenghts+sum_weak+sum_opport+sum_threats)
print(sum_power)

list_sum=[sum_strenghts,sum_weak,sum_opport,sum_threats,sum_power]
list_names=["Strenghts","Weaknesses","Opportunities","Treats","Overall"]

import matplotlib.pyplot as plt
fig=plt.figure(figsize=(16,12), dpi=75)
plt.title('SWOT-анализ',fontsize=40)
plt.xlabel('Свойства',fontsize=25)
plt.ylabel('Важность',fontsize=25)
plt.bar (list_names, list_sum, width=0.6)
plt.xticks(list_names, fontsize=15)

plt.grid(True, color='r', linestyle='-', linewidth=0.8)
plt.draw
plt.show

print("Strenghts= ", sum_strenghts)
print("Weaknesses= ", sum_weak)
print("Opportunities= ", sum_opport)
print("Threats= ", sum_threats)
print("Overall= ", sum_power)